--EXEMPLOS USANDO JOIN

--CRIAÇÃO DA TABELA ALUNOS
CREATE TABLE ALUNOS(
	ID_ALUNO INT IDENTITY(1,1),
	NOME VARCHAR(20) NOT NULL
)

--CRIAÇÃO DA TABELA DISCIPLINA
CREATE TABLE DISCIPLINA(
	ID_DISCIPLINA INT IDENTITY(1,1),
	NOME_DISC VARCHAR(20) NOT NULL
)

--CRIAÇÃO DA TABELA MATRÍCULA
CREATE TABLE MATRICULA(
	ID_ALUNO INT,
	ID_DISCIPLINA INT,
	PERIODO VARCHAR(10)
)

--ALTERANDO CAMPOS DA TABELA MATRICULA PARA NÃO PERMITIR NULL
ALTER TABLE MATRICULA ALTER COLUMN ID_ALUNO INT NOT NULL
ALTER TABLE MATRICULA ALTER COLUMN ID_DISCIPLINA INT NOT NULL

--CRIANDO CHAVE PRIMARIA COMPOSTA
ALTER TABLE MATRICULA ADD CONSTRAINT PK_1 PRIMARY KEY(ID_ALUNO, ID_DISCIPLINA)
--CRIANDO CHAVE PRIMÁRIA NA TABELA DISCIPLINA
ALTER TABLE DISCIPLINA ADD CONSTRAINT PK_2 PRIMARY KEY (ID_DISCIPLINA)
--CRIANDO CHAVE PRIMÁRIA NA TABELA ALUNOS
ALTER TABLE ALUNOS ADD CONSTRAINT PK_3 PRIMARY KEY (ID_ALUNO)

--ADICIONANDO AS CHAVES ESTRANGEIRAS NA TABELA MATRICULA
ALTER TABLE MATRICULA ADD CONSTRAINT FK_MAT1 FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID_ALUNO)
ALTER TABLE MATRICULA ADD CONSTRAINT FK_MAT2 FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINA(ID_DISCIPLINA)


--INSERINDO REGISTROS NA TABELA ALUNOS
INSERT INTO ALUNOS VALUES ('João'), ('Maria'), ('Pedro'), ('Tiago'), ('Henrique')

--INSERINDO REGISTROS NA TABELA DE DISCIPLINAS
INSERT INTO DISCIPLINA VALUES ('Física'), ('Química'), ('Matemática'), ('Banco de Dados'), ('Programação')

--INSERINDO REGISTROS NA TABELA DE MATRICULA
INSERT INTO MATRICULA VALUES ('1', '1', 'NOTURNO'), ('1', '2', 'VESPERTINO'), ('1', '3', 'MATUTINO'),
('2', '3', 'NOTURNO'), ('2', '4', 'NOTURNO'), ('3', '1', 'NOTURNO'), ('3', '3', 'NOTURNO'), 
('3', '4', 'NOTURNO'), ('5', '1', 'MATUTINO'), ('5', '2', 'VESPERTINO'), ('5', '4', 'NOTURNO')


--ALUNO COM O COD 4 NÃO TEM MATRÍCULA
--DISCIPLINA 5 NÃO TEM ALUNOS

--INNER JOIN
SELECT A.NOME AS ALUNO, C.NOME_DISC AS DISCIPLINA, B.PERIODO
FROM ALUNOS A
INNER JOIN MATRICULA B
	ON A.ID_ALUNO = B.ID_ALUNO 
INNER JOIN DISCIPLINA C
	ON B.ID_DISCIPLINA = C.ID_DISCIPLINA

--LEFT JOIN
SELECT A.NOME AS ALUNO, C.NOME_DISC AS DISCIPLINA, B.PERIODO
FROM ALUNOS A
LEFT JOIN MATRICULA B
	ON A.ID_ALUNO = B.ID_ALUNO 
LEFT JOIN DISCIPLINA C
	ON B.ID_DISCIPLINA = C.ID_DISCIPLINA

SELECT A.NOME AS ALUNO, C.NOME_DISC AS DISCIPLINA, B.PERIODO
FROM ALUNOS A
LEFT JOIN MATRICULA B
	ON A.ID_ALUNO = B.ID_ALUNO 
LEFT JOIN DISCIPLINA C
	ON B.ID_DISCIPLINA = C.ID_DISCIPLINA
WHERE C.NOME_DISC IS NULL

--RIGHT JOIN
SELECT A.NOME AS ALUNO, C.NOME_DISC AS DISCIPLINA, B.PERIODO
FROM ALUNOS A
RIGHT JOIN MATRICULA B
	ON A.ID_ALUNO = B.ID_ALUNO 
RIGHT JOIN DISCIPLINA C
	ON B.ID_DISCIPLINA = C.ID_DISCIPLINA

--FULL JOIN
SELECT A.NOME AS ALUNO, C.NOME_DISC AS DISCIPLINA, B.PERIODO
FROM ALUNOS A
FULL JOIN MATRICULA B
	ON A.ID_ALUNO = B.ID_ALUNO 
FULL JOIN DISCIPLINA C
	ON B.ID_DISCIPLINA = C.ID_DISCIPLINA