--AULA DE EXTENSÃO SQL: IF ELSE


--PRIMEIRO EXEMPLO: AND
IF 1 = 1 AND 2 = 2
	BEGIN 
		PRINT 'SÃO IGUAIS'
	END
	ELSE
		PRINT 'SÃO DIFERENTES'

--SEGUNDO EXEMPLO: AND
IF 1 = 1 AND 2 = 17
	BEGIN 
		PRINT 'SÃO IGUAIS'
	END
	ELSE
		PRINT 'SÃO DIFERENTES'

--TERCEIRO EXEMPLO: OR
IF 1 = 1 OR 2 = 17
	BEGIN
		PRINT 'CORRETO'
	END
	ELSE
		PRINT 'FALSO'

--QUARTO EXEMPLO:
--CRIAÇÃO DA TABELA

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PED_DETALHE')
	BEGIN
		DROP TABLE ped_detalhe
	END
ELSE
	BEGIN
		SELECT A.OrderID PEDIDO, 
			   A.ProductID COD_MAT, 
			   A.Quantity QTD,
			   A.UnitPrice PREÇO
		  INTO ped_detalhe
		  FROM NORTHWND.dbo.[Order Details] A
	END

--verificando a tabela
SELECT   PEDIDO, COUNT(*)
FROM     ped_detalhe 
GROUP BY PEDIDO

--TESTE COM IF ELSE
DECLARE @PEDIDO INT;
SET @PEDIDO = '10789';
IF (SELECT COUNT(*) 
	FROM   ped_detalhe WHERE PEDIDO = @PEDIDO 
	GROUP BY PEDIDO) < 3
	BEGIN
		PRINT 'CONDIÇÃO SATISFEITA'
	END
	ELSE
		BEGIN
			SELECT  'OS ITENS DO PEDIDO SÃO: ' MSG,
					PEDIDO, 
					COD_MAT
			  FROM  ped_detalhe 
			 WHERE  PEDIDO = @PEDIDO
		END

--IF DECLARAÇÃO DE VARIÁVEL
--declaração
DECLARE @IDADE INT
--atribuição do valor
SET @IDADE = 15
--Se for menor do que 18 anos
IF @IDADE < 18
	PRINT 'MENOR QUE 18 ANOS'
--Se  a idade estiver entre 18 e 65 anos
ELSE IF @IDADE >= 18 AND @IDADE <= 65
	PRINT 'ENTRE 18 E 65 ANOS'
ELSE
	PRINT 'MAIOR QUE 65 ANOS'
	
