--Funções de Data e Hora / DATEADD


--ADICIONANDO 7 DIAS A PARTIR DE 11/06/2022
SELECT DATEADD(DAY, 7, '11-06-2022')

--ADICIONANDO 90 DIAS
SELECT GETDATE() AS AGORA,
	   DATEADD(DAY, 90, GETDATE());

--ADICIONANDO 2 MESES
SELECT GETDATE() AS AGORA,
	   DATEADD(MONTH, 2, GETDATE());

--ADICIONANDO 3 ANOS
SELECT GETDATE() AS AGORA,
	   DATEADD(YEAR, 3, GETDATE());

--EXEMPLO
USE NORTHWND
SELECT A.OrderID,
	   A.OrderDate,
	   DATEADD(DAY, 7, A.OrderDate) AS ADD_DAY,
	   DATEADD(MONTH, 2, A.OrderDate) AS ADD_MONTH,
	   DATEADD(YEAR, 3, A.OrderDate) AS ADD_YEAR
FROM   Orders A
