--Funções de Data e Hora - DATEDIFF


--DIFERENÇA EM DIAS
SELECT DATEDIFF(DAY, '2015-03-12', '2017-07-13') AS DIFF_DAY;

--DIFERENÇA EM MESES
SELECT DATEDIFF(MONTH, '2015-03-12', '2017-07-13') AS DIFF_MONTH;

--DIFERENÇA EM ANOS
SELECT DATEDIFF(YEAR, '2015-03-12', '2017-07-13') AS DIFF_YEAR;


--DESCOBRIR HÁ QUANTOS DIAS/MESES/ANOS NASCEMOS
--DIAS
SELECT DATEDIFF(DAY, '1997-10-08', GETDATE()) AS DAYS_OLD;
--MESES
SELECT DATEDIFF(MONTH, '1997-10-08', GETDATE()) AS MONTHS_OLD;
--YEARS
SELECT DATEDIFF(YEAR, '1997-10-08', GETDATE()) AS YEARS_OLD;
--DIFERENÇA DE 7 DIAS
SELECT DATEDIFF(DAY, '11-06-2022', DATEADD(DAY, 7, '11-06-2022')) AS DIF;


--EXEMPLO 1
USE NORTHWND

SELECT A.CustomerID,
	   A.OrderDate,
	   A.RequiredDate,
	   DATEDIFF(DAY, A.OrderDate, A.RequiredDate) AS DIF_DAY,
	   DATEDIFF(MONTH, A.OrderDate, A.RequiredDate) AS DIF_MONTH,
	   DATEDIFF(YEAR, A.OrderDate, A.RequiredDate) AS DIF_YEAR
FROM   Orders A

--EXEMPLO 2
SELECT A.CustomerID,
	   A.OrderDate,
	   A.RequiredDate,
	   DATEDIFF(DAY, A.OrderDate, A.RequiredDate) AS DIF_DAY,
	   DATEDIFF(MONTH, A.OrderDate, A.RequiredDate) AS DIF_MONTH,
	   DATEDIFF(YEAR, A.OrderDate, A.RequiredDate) AS DIF_YEAR
FROM   Orders A
WHERE  DATEDIFF(DAY, A.OrderDate, A.RequiredDate) = 28
