--DATA CONTROL LANGUAGE PARTE 1: CONCEDE-GRANT

--Cria um usuário e dá permissões a ele no banco
CREATE LOGIN UsrTest WITH PASSWORD='SenhaTest'
exec master.dbo.sp_addlogin 'UsrTeste3', 'SenhaTeste3'

--outras procedures
exec sp_grantdbaccess 'UsrTest','SenhaTest'
exec sp_revokedbaccess 'UsrTest'
exec sp_droplogin 'UsrTeste3'


--inserindo o usuário na base de dados
CREATE USER UsrTest FOR LOGIN UsrTest WITH DEFAULT_SCHEMA = dbo

--Concedendo Acesso de Atualização ao usuário
GRANT UPDATE ON FUNCIONARIOS TO UsrTest;
--Concedendo Acesso de Inserção
GRANT INSERT ON FUNCIONARIOS TO UsrTest;
--Concedendo Acesso de Leitura
GRANT SELECT ON FUNCIONARIOS TO UsrTest;
--Concedendo Acesso de Exclusão
GRANT DELETE ON FUNCIONARIOS TO UsrTest;


--CRIANDO UMA PROCEDURE PARA TESTE
CREATE PROCEDURE sp_testproc
AS
SELECT * FROM cidades

--EXECUTANDO PROCEDURE DE TESTE
EXEC sp_testproc

--Concedendo acesso para executar procedures
GRANT EXECUTE ON sp_testproc TO Usrtest

--VERIFICANDO USUÁRIO LOGADO
SELECT CURRENT_USER
--ALTERANDO USUÁRIO LOGADO
SETUSER 'UsrTest'

--Executando procedure com usuário teste
EXEC sp_testproc
--TESTANDO SELECT
SELECT * FROM FUNCIONARIOS
--TESTANDO O INSERT
INSERT INTO FUNCIONARIOS VALUES ('Maria', 2200,'TI')
--TESTANDO UPDATE
UPDATE FUNCIONARIOS SET NOME='Marisa' WHERE ID=6
--TESTANDO DELETE
DELETE FUNCIONARIOS WHERE ID=6


--DATA CONTROL LANGUAGE PARTE 2: REVOGA-REVOKE

--REVOGANDO ACESSO DE ATUALIZAÇÃO
REVOKE UPDATE ON FUNCIONARIOS TO UsrTest
--REVOGANDO ACESSO DE INSERÇÃO
REVOKE INSERT ON FUNCIONARIOS TO UsrTest
--REVOGANDO ACESSO DE LEITURA
REVOKE SELECT ON FUNCIONARIOS TO UsrTest
--REVOGANDO DIREITO DE EXECUÇÃO DE PROCEDURE
REVOKE EXECUTE ON sp_testproc TO UsrTest

--VERIFICANDO USUÁRIO LOGADO
SELECT CURRENT_USER

--ALTERANDO O USUÁRIO
SETUSER 'UsrTest'

--Executando procedure com usuário teste
EXEC sp_testproc
--TESTANDO SELECT
SELECT * FROM FUNCIONARIOS
--TESTANDO O INSERT
INSERT INTO FUNCIONARIOS VALUES ('Maria', 2200,'TI')
--TESTANDO UPDATE
UPDATE FUNCIONARIOS SET NOME='Marisa' WHERE ID=6
--TESTANDO DELETE
DELETE FUNCIONARIOS WHERE ID=7


--DATA CONTROL LANGUAGE PARTE 3: NEGA-DENY


--NEGANDO ACESSO DE ATUALIZAÇÃO
DENY UPDATE ON FUNCIONARIOS TO UsrTest
--NEGANDO ACESSO DE INSERÇÃO
DENY INSERT ON FUNCIONARIOS TO UsrTest
--NEGANDO ACESSO DE LEITURA
DENY SELECT ON FUNCIONARIOS TO UsrTest
--NEGANDO ACESSO DE DELEÇÃO
DENY DELETE ON FUNCIONARIOS TO UsrTest
--NEGANDO DIREITO A EXECUÇÃO DE PROCEDURE
DENY EXECUTE ON sp_testproc TO UsrTest

--VERIFICANDO USUÁRIO LOGADO
SELECT CURRENT_USER

--ALTERANDO O USUÁRIO
SETUSER 'UsrTest'

--Executando procedure com usuário teste
EXEC sp_testproc
--TESTANDO SELECT
SELECT * FROM FUNCIONARIOS
--TESTANDO O INSERT
INSERT INTO FUNCIONARIOS VALUES ('Maria', 2200,'TI')
--TESTANDO UPDATE
UPDATE FUNCIONARIOS SET NOME='Marisa' WHERE ID=6
--TESTANDO DELETE
DELETE FUNCIONARIOS WHERE ID=8