--DDL - Criação de tabela para exercício
CREATE TABLE FUNCIONARIOS(
	ID INT IDENTITY(1,1),
	NOME VARCHAR(50) NOT NULL,
	SALARIO DECIMAL(10,2),
	SETOR VARCHAR(30)
)

--DML SELECT
--EXEMPLO SELECT
	SELECT * FROM FUNCIONARIOS
--EXEMPLO SELECT
	SELECT NOME,
		   SETOR
	FROM FUNCIONARIOS
--EXEMPLO SELECT
	SELECT NOME,
		   SETOR AS DEPTO
	FROM FUNCIONARIOS

--DML INSERT
	INSERT INTO FUNCIONARIOS VALUES ('Joao', 1000,''), ('Jose', 2000,''), ('Alexandre', 3000, '')
-- OU
	INSERT INTO FUNCIONARIOS (NOME, SALARIO) VALUES ('Pedro', 1000)

--DML UPDATE
	UPDATE FUNCIONARIOS SET SALARIO = 1500
	WHERE ID = 1

	UPDATE FUNCIONARIOS SET SALARIO = SALARIO*1.5
	WHERE ID = 1

--DML UPDATE COM MAIS DE UM CAMPO
	UPDATE FUNCIONARIOS SET SALARIO = 1500, SETOR = 'TI'
	WHERE ID <> 1

--DML DELETE
	DELETE FUNCIONARIOS WHERE ID = 1