SELECT SYSDATETIME() AS SYSDATETIME;
SELECT SYSDATETIMEOFFSET() AS SYSDATETIMEOFFSET;
SELECT SYSUTCDATETIME() AS SYSUTCDATETIME;
SELECT CURRENT_TIMESTAMP AS 'CURRENT TIMESTAMP';
SELECT GETDATE() AS GETDATE;
SELECT GETUTCDATE() AS GETUTCDATE
