--problema
SELECT 100/0
--TRATANDO O PROBLEMA

SELECT ISNULL(100 / NULLIF(0,0), 0)
SELECT ISNULL(1/NULLIF(0,0), 0)
SELECT ISNULL(100/NULLIF(50,0), 0)

--CRIANDO TABELA
USE CURSO
CREATE TABLE TESTE
(
	VAL1 INT,
	VAL2 INT
)

--POPULANDO TABELA
INSERT INTO TESTE VALUES (100,0), (100,25), (1,0), (5,2)

--VERIFICANDO DADOS
SELECT * FROM TESTE

--EXPRESSÃO
SELECT VAL1, 
       VAL2, 
	   VAL1/VAL2 AS RESULT 
FROM   TESTE

--TRATANDO OS ERROS DA EXPRESSÃO ACIMA
SELECT VAL1,
	   VAL2,
	   ISNULL(VAL1/NULLIF(VAL2,0), 0) AS RESULT,
	   ISNULL(CAST (VAL1 AS DECIMAL(5,2))/NULLIF(VAL2,0), 0) AS RESULT_
FROM   TESTE