--FUNÇÕES DE DATA E HORA

--DATENAME
SELECT DATENAME(DAY, GETDATE()) AS DAY,
	   DATENAME(MONTH, GETDATE()) AS MONTH,
	   DATENAME(YEAR, GETDATE()) AS YEAR

--DATEPART
SELECT DATEPART(DAY, GETDATE()) AS DAY,
       DATEPART(MONTH, GETDATE()) AS MONTH,
	   DATEPART(YEAR, GETDATE()) AS YEAR

--FUNÇÕES DIRETAS
SELECT DAY(GETDATE()) AS DAY,
	   MONTH(GETDATE()) AS MONTH,
	   YEAR(GETDATE()) AS YEAR

SELECT DATETIMEFROMPARTS(2022,6,2,21,48,0,1)


--EXEMPLO 1
USE NORTHWND
SELECT A.OrderID,
	   A.OrderDate ORDER_DATE,
	   MONTH(A.OrderDate) MONTH,
	   YEAR(A.OrderDate) AS YEAR 
	   FROM Orders A

--EXEMPLO 2
SELECT YEAR(OrderDate) YEAR,
	   MONTH(OrderDate) MONTH,
	   DAY(OrderDate) DAY,
	   COUNT(*) AS AMOUNT
FROM Orders
	   GROUP BY OrderDate
	   ORDER BY OrderDate

--EXEMPLO 3
SELECT YEAR(OrderDate) YEAR,
	   COUNT(*) AS AMOUNT
FROM Orders
	   GROUP BY YEAR(OrderDate)
	   ORDER BY YEAR(OrderDate)