--Extensão SQL: Estruturas de repetição WHILE

--EXEMPLO 1
DECLARE @COUNT INT
SET @COUNT = 100

WHILE (SELECT @COUNT) >= 50
	BEGIN
		PRINT @COUNT
		SET @COUNT = @COUNT - 10
	END

-- BREACK CONTINUE
DECLARE @COUNT2 INT
SET @COUNT2 = 10
WHILE(SELECT GETDATE() - @COUNT2) <= GETDATE()
	BEGIN
		PRINT GETDATE() - @COUNT2
		SET @COUNT2 = @COUNT2 - 1
		IF(GETDATE() - @COUNT2) >= GETDATE()
			BREAK
		ELSE
			CONTINUE
	END

--EXEMPLO TABUADA

DECLARE @NUMBER INT
DECLARE @MULTIPLIER INT

SET @NUMBER = 0
SET @MULTIPLIER = 2

WHILE(@NUMBER <= 10)
	BEGIN
		PRINT CAST(@NUMBER AS NVARCHAR) + N' X ' + CAST(@MULTIPLIER AS NVARCHAR) + N' = ' + CAST(@NUMBER*@MULTIPLIER AS NVARCHAR)
		SET @NUMBER = @NUMBER + 1 
	END

--EXEMPLO MOSTRAR NUMERO PAR OU ÍMPAR 
DECLARE @NUM INT
DECLARE @MAX INT
DECLARE @MOD INT
SET @NUM = 1
SET @MAX = 10

WHILE(@NUM <= @MAX )
	BEGIN
		SET @MOD = @NUM%2
		IF(@MOD = 0)
			PRINT CAST(@NUM AS NVARCHAR) + ' É PAR'
		ELSE
			PRINT CAST(@NUM AS NVARCHAR) + ' É ÍMPAR'
		SET @NUM = @NUM + 1
		SET @MOD = 0
	END