--Extensão SQL: Estruturas de repetição WHILE

--EXEMPLO 1
DECLARE @COUNT INT
SET @COUNT = 100

WHILE (SELECT @COUNT) >= 50
	BEGIN
		PRINT @COUNT
		SET @COUNT = @COUNT - 10
	END

-- BREACK CONTINUE
DECLARE @COUNT2 INT
SET @COUNT2 = 10
WHILE(SELECT GETDATE() - @COUNT2) <= GETDATE()
	BEGIN
		PRINT GETDATE() - @COUNT2
		SET @COUNT2 = @COUNT2 - 1
		IF(GETDATE() - @COUNT2) >= GETDATE()
			BREAK
		ELSE
			CONTINUE
	END

--EXEMPLO TABUADA

DECLARE @NUMBER INT
DECLARE @MULTIPLIER INT

SET @NUMBER = 0
SET @MULTIPLIER = 2

WHILE(@NUMBER <= 10)
	BEGIN
		PRINT CAST(@NUMBER AS NVARCHAR) + N' X ' + CAST(@MULTIPLIER AS NVARCHAR) + N' = ' + CAST(@NUMBER*@MULTIPLIER AS NVARCHAR)
		SET @NUMBER = @NUMBER + 1 
	END

--EXEMPLO MOSTRAR NUMERO PAR OU ÍMPAR 
DECLARE @NUM INT
DECLARE @MAX INT
DECLARE @MOD INT
SET @NUM = 1
SET @MAX = 10

WHILE(@NUM <= @MAX )
	BEGIN
		SET @MOD = @NUM%2
		IF(@MOD = 0)
			PRINT CAST(@NUM AS NVARCHAR) + ' É PAR'
		ELSE
			PRINT CAST(@NUM AS NVARCHAR) + ' É ÍMPAR'
		SET @NUM = @NUM + 1
		SET @MOD = 0
	END

--EXEMPLO: ALIMENTAÇÃO DE TABELA
USE CURSO
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'DIM_DATA')
	DROP TABLE DIM_DATA
GO
	CREATE TABLE DIM_DATA(
		ID_DIM_DATA INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
		DIM_DATA DATE NOT NULL,
		ANO SMALLINT NOT NULL,
		MES SMALLINT NOT NULL,
		DIA SMALLINT NOT NULL,
		DIA_SEMANA SMALLINT NOT NULL,
		DIA_UTIL CHAR(1) NOT NULL,
		FIM_SEMANA CHAR(1) NOT NULL,
		FERIADO CHAR(1) NOT NULL,
		NOME_FERIADO VARCHAR(30) NOT NULL,
		NOME_DIA_SEMANA VARCHAR(15) NOT NULL,
		NOME_DIA_SEMANA_ABREV CHAR(3) NOT NULL,
		NOME_MES VARCHAR(15) NOT NULL,
		NOME_MES_ABREV CHAR(3) NOT NULL,
		BIMESTRE SMALLINT NOT NULL,
		TRIMESTRE SMALLINT NOT NULL,
		SEMESTRE SMALLINT NOT NULL
	)
	--SELECT * FROM DIM_DATA

	DECLARE @dataINICIAL DATE,
			@dataFINAL DATE,
			@DATA DATE,
			@ANO SMALLINT,
			@MES SMALLINT,
			@DIA SMALLINT,
			@diaSEMANA SMALLINT,
			@diaUTIL CHAR(1),
			@fimSEMANA CHAR(1),
			@FERIADO CHAR(1),
			@nomeFERIADO VARCHAR(30),
			@nomeDiaSemana VARCHAR(15),
			@nomeDiaSemanaAbrev CHAR(3),
			@nomeMes VARCHAR(15),
			@nomeMesAbrev CHAR(3),
			@BIMESTRE SMALLINT,
			@TRIMESTRE SMALLINT,
			@SEMESTRE SMALLINT

--informe aqui o período para o qual deseja criar os dados
SET @dataINICIAL = '01/01/2022'
SET @dataFINAL = '31/12/2022'

WHILE @dataINICIAL <= @dataFINAL
	BEGIN
		SET @DATA = @dataINICIAL
		SET @ANO = YEAR(@DATA)
		SET @MES = MONTH(@DATA)
		PRINT @MES
		SET @DIA = DAY(@DATA)
		SET @diaSEMANA = DATEPART(WEEKDAY, @DATA)
		IF @diaSEMANA IN (1,7)
			SET @fimSEMANA = 'S'
		ELSE
			SET @fimSEMANA = 'N'
	


	IF(@MES = 1 AND @DIA = 1)
		SET @nomeFERIADO = 'CONFRATERNIZAÇÃO UNIVERSAL'
	ELSE
	IF(@MES = 4 AND @DIA = 21)
		SET @nomeFERIADO = 'TIRADENTES'
	ELSE
	IF(@MES = 5 AND @DIA = 1)
		SET @nomeFERIADO = 'DIA DO TRABALHO'
	ELSE
	IF(@MES = 9 AND @DIA = 7)
		SET @nomeFERIADO = 'INDEPENDÊNCIA DO BRASIL'
	ELSE
	IF(@MES = 10 AND @DIA = 12)
		SET @nomeFERIADO = 'NOSSA SENHORA APARECIDA'
	ELSE
	IF(@MES = 11 AND @DIA = 2)
		SET @nomeFERIADO = 'DIA DOS FINADOS'
	ELSE
	IF(@MES = 11 AND @DIA = 15)
		SET @nomeFERIADO = 'PROCLAMAÇÃO DA REPÚBLICA'
	ELSE
	IF(@MES = 12 AND @DIA = 25)
		SET @nomeFERIADO = 'NATAL'
	ELSE
		SET @nomeFERIADO = ''
	

	IF(@MES = 1 AND @DIA = 1) OR
	 (@MES = 4 AND @DIA = 21) OR
	 (@MES = 5 AND @DIA = 1) OR
	 (@MES = 9 AND @DIA = 7) OR
	 (@MES = 10 AND @DIA = 12) OR
	 (@MES = 11 AND @DIA = 2) OR
	 (@MES = 11 AND @DIA = 15) OR
	 (@MES = 12 AND @DIA = 25)
		SET @FERIADO = 'S'
	ELSE
		SET @FERIADO = 'N'

	SET @nomeMes = 
	CASE
		WHEN @MES = 1 THEN 'JANEIRO'
		WHEN @MES = 2 THEN 'FEVEREIRO'
		WHEN @MES = 3 THEN 'MARÇO'
		WHEN @MES = 4 THEN 'ABRIL'
		WHEN @MES = 5 THEN 'MAIO'
		WHEN @MES = 6 THEN 'JUNHO'
		WHEN @MES = 7 THEN 'JULHO'
		WHEN @MES = 8 THEN 'AGOSTO'
		WHEN @MES = 9 THEN 'SETEMBRO'
		WHEN @MES = 10 THEN 'OUTUBRO'
		WHEN @MES = 11 THEN 'NOVEMBRO'
		WHEN @MES = 12 THEN 'DEZEMBRO'
	END

	SET @nomeMesAbrev = 
	CASE
		WHEN @MES = 1 THEN 'JAN'
		WHEN @MES = 2 THEN 'FEV'
		WHEN @MES = 3 THEN 'MAR'
		WHEN @MES = 4 THEN 'ABR'
		WHEN @MES = 5 THEN 'MAI'
		WHEN @MES = 6 THEN 'JUN'
		WHEN @MES = 7 THEN 'JUL'
		WHEN @MES = 8 THEN 'AGO'
		WHEN @MES = 9 THEN 'SET'
		WHEN @MES = 10 THEN 'OUT'
		WHEN @MES = 11 THEN 'NOV'
		WHEN @MES = 12 THEN 'DEZ'
	END

	IF @fimSEMANA = 'S' OR @FERIADO = 'S'
		SET @diaUTIL = 'N'
	ELSE
		SET @diaUTIL = 'S'

	SET @nomeDiaSemana =
	CASE
		WHEN @diaSEMANA = 1 THEN 'DOMINGO'
		WHEN @diaSEMANA = 2 THEN 'SEGUNDA-FEIRA'
		WHEN @diaSEMANA = 3 THEN 'TERÇA-FEIRA'
		WHEN @diaSEMANA = 4 THEN 'QUARTA-FEIRA'
		WHEN @diaSEMANA = 5 THEN 'QUINTA-FEIRA'
		WHEN @diaSEMANA = 6 THEN 'SEXTA-FEIRA'
		WHEN @diaSEMANA = 7 THEN 'SÁBADO' 
	END

	SET @nomeDiaSemanaAbrev =
	CASE
		WHEN @diaSEMANA = 1 THEN 'DOM'
		WHEN @diaSEMANA = 2 THEN 'SEG'
		WHEN @diaSEMANA = 3 THEN 'TER'
		WHEN @diaSEMANA = 4 THEN 'QUA'
		WHEN @diaSEMANA = 5 THEN 'QUI'
		WHEN @diaSEMANA = 6 THEN 'SEX'
		WHEN @diaSEMANA = 7 THEN 'SAB' 
	END

	SET @BIMESTRE =
	CASE
		WHEN @MES IN (1,2) THEN 1
		WHEN @MES IN(3,4) THEN 2
		WHEN @MES IN(5,6) THEN 3
		WHEN @MES IN(7,8) THEN 4
		WHEN @MES IN (9,10) THEN 5
		WHEN @MES IN (11,12) THEN 6
	END

	SET @TRIMESTRE =
	CASE
		WHEN @MES IN (1,2,3) THEN 1
		WHEN @MES IN(4,5,6) THEN 2
		WHEN @MES IN(7,8,9) THEN 3
		WHEN @MES IN(10,11,12) THEN 4
	END

	SET @SEMESTRE = 
	CASE
		WHEN @MES BETWEEN 1 AND 6 THEN 1
		WHEN @MES BETWEEN 7 AND 12 THEN 2 
	END

	INSERT INTO DIM_DATA (
		DIM_DATA,
		ANO,
		MES,
		DIA,
		DIA_SEMANA,
		DIA_UTIL,
		FIM_SEMANA,
		FERIADO,
		NOME_FERIADO,
		NOME_DIA_SEMANA,
		NOME_DIA_SEMANA_ABREV,
		NOME_MES,
		NOME_MES_ABREV,
		BIMESTRE,
		TRIMESTRE,
		SEMESTRE
	)
	
	VALUES (
			@DATA,
			@ANO,
			@MES,
			@DIA,
			@diaSEMANA,
			@diaUTIL,
			@fimSEMANA,
			@FERIADO,
			@nomeFERIADO,
			@nomeDiaSemana,
			@nomeDiaSemanaAbrev,
			@nomeMes,
			@nomeMesAbrev,
			@BIMESTRE,
			@TRIMESTRE,
			@SEMESTRE
	)
 SET @dataINICIAL = DATEADD(DAY,1,@dataINICIAL)
 END
 SELECT * FROM DIM_DATA