--FUNCOES DE CADEIAS DE CARACTERES

--exemplo ASCII
SELECT ASCII('SQL')
SELECT ASCII('S')
SELECT ASCII('Q')
SELECT ASCII('L')



DECLARE @POSITION INT,
@STRING CHAR(9)

SET @POSITION=1;
SET @STRING = 'Olá mundo';

		WHILE @POSITION <= DATALENGTH(@STRING)
			BEGIN
				SELECT ASCII(SUBSTRING(@STRING, @POSITION, 1)) as code_ascii,
				CHAR(ASCII(SUBSTRING(@STRING, @POSITION, 1))) as code_char
				SET @POSITION = @POSITION + 1;
			END;

--LTRIM
--RETORNA UMA EXPRESSÃO DE CARACTERES DEPOIS DE REMOVER ESPAÇOS EM BRANCO À ESQUERDA

DECLARE @string_to_trim VARCHAR(60)
SET @string_to_trim = '     CINCO ESPAÇOS NO INÍCIO'
SELECT 'TEXTO SEM ESPAÇO: ' +  LTRIM(@string_to_trim)
SELECT 'TEXTO COM ESPAÇO: ' + @string_to_trim